#!/bin/bash

echo "^.^ ,~={( RUNNING PROGRAM AND GENERATING \"README.Md\" FILE )}~!"

./bootstrap |tee ./ai/logs/output.log

echo
echo "GENERATING \"README.md\" TEXT FILE."

cat ./ai/log/addy/readme_component_1.txt > README.md
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<" >> README.md
cat ./ai/log/output.log >> README.md
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<" >> README.md
cat ./ai/log/addy/beneficial.txt >> README.md
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<" >> README.md
cat ./ai/log/addy/readme_component_2.txt >> README.md

echo "done."
exit 0
