#!/usr/bin/bash

### BASIC RUN SCRIPT (can be used with arguments) ###

echo
echo "~:start."
echo
./start $@  # runs the Ai model
echo "~:completing readme."
echo
./readme.sh # copies README.md from ./doc
echo
echo "(Model-Ai) https://model-ai.com"
echo

exit 0