#!/bin/bash

### DOWNLOADS ###
LOGDIR="./ai/patch/logs"
DESTINATION="./ai/patch/dl"
FILENAME="archives_list.csv"
LOGFILE="wlog.txt"
LIST_URL_ROOT="https://model-ai.com/archive"
LIST_URL="$LIST_URL_ROOT/$FILENAME"   # might contain additional archives

### PATCHING ###
DLCSV="$1"
DESTINATION="./ai/patching/files/"
LOCATION=$DESTINATION
FILENAME="archives_list.csv"

### FILENAMES ###
#ARCHIVE1="./ai/patch/archive1.tar.gz"
#ARCHIVE2="./ai/patch/archive2.tar.gz"
#ARCHIVE2="./ai/patch/archive3.tar.gz"
#EXTRA="./ai/patch/extra.txt"

#ARCHIVE_URL1="https://model-ai.com/archive/archive1.tar.gz"
#ARCHIVE_URL2="https://model-ai.com/archive/archive2.tar.gz"
#ARCHIVE_URL3="https://model-ai.com/archive/archive3.tar.gz"
#EXTRA_URL="https://model-ai.com/archive/extra.txt"

### URLS ###

### ARCHIVES IN REPOSITORY ###

### GET ARCHIVE FILES LIST FETCHED FROM THE REPOSITORY URLS ABOVE AT HTTPS://MODEL-AI.COM
echo "-/- getting \"archives_list.csv\""
wget --output-file="$LOGDIR/$LOGFILE" $LIST_URL

#echo "-/- getting \"archives\" (.tar.gz format) from online repository"
#wget --output-file=$ARCHIVE1 $ARCHIVE_URL1
#wget --output-file=$ARCHIVE2 $ARCHIVE_URL2
#wget --output-file=$ARCHIVE3 $ARCHIVE_URL3

### FETCH EXTRA DATA ###
#wget --output-file=$EXTRA $EXTRA_URL

### DONE WITH THE DOWNLOADS ###
echo "-/- done with downloads."

### PATCH ###
echo
echo "~/~ patching."
echo "patching: \"$FILENAME\" (archives)"
echo

if [ -f "./$FILENAME" ]
  then
  echo "+OK"
  mv "./$FILENAME" $DESTINATION
  elif [ -d "$DESTINATION" ]
  then
  cp "./$FILENAME" $LOCATION
  export model_ai_patched="a0+ok"
  echo "+OK (1)"
  elif [ -f "./run" ]
  then
  mkdir -p $DESTINATION
  cp "./$FILENAME" $DESTINATION
  export model_ai_patched="a1+ok"
  echo "+OK (2)"
  else
  export model_ai_patched="not+ok"
  echo "+NOT_OK(3)"
  exit 1
fi

#export modelai-patched=a2ok

if [ -f "$LOCATION/$FILENAME" ]
  then
  ### OPEN FILE AND FETCH ARCHIVES HERE ###
    ### DO LOGIC HERE ###


  ### PATCHING OK ###
  echo "PATCHING +OK"
  exit 0
  else
  echo "PATCHING +NOT_OK"
  exit 1
fi

#export modelai-patched=aok
