// ./AI/VIRTUAL/CREATION/TOOL.CPP -- USED TO CREATE THE "TOOL" EXECUTABLE.
// "TOOL" PROGRAM.

// THE TOOL PROGRAM WILL CHECK THE CHECKSUMS FOR ALL FILES INTEGRITY
// ALSO WILL SET ALL THE EXECUTE PERMISSIONS FOR ALL THE SCRIPTS (HANDLED BY "AI/BIN/SCRIPT/PERM" NOW)
// ALSO WILL HANDLE CREATION OF THE VIRTUAL FILESYSTEM (INCLUDING ALL THE FILES AND COMPILE THE "VIRTUAL-CD")

#include <iostream>

using namespace std;

int main(int argc, char *argv[]) {

    std::cout << "tool://matrix" << std::endl;

return 0;
}