#!/bin/bash

echo "~:deploying \"tool\"."

DIRECTORY="./ai/virtual/creation"
OUTPUTFILE="./ai/virtual/creation/tool"

### compile tool program
g++ -o $OUTPUTFILE $DIRECTORY/tool.cpp

if [ -f "$DIRECTORY/tool" ]
  then
  echo "~:compilation finished."
fi

echo "~:exiting script."
echo "done."

exit 0